[package]
name = "one_period_shortage"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "one_period_shortage"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
statrs = "0.17"
